\begin{tetris}[bsc_cis_biochemie]
	\drawsemester{1. Semester\\(WiSe)}
		\drawmodule{6}{tetris_blue}{transparent}{black}{Softwareentwicklung I}
		\drawmodule{9}{tetris_red}{transparent}{black}{Allgemeine und\\{}Anorganische Chemie}
		\drawmodule{4.5}{tetris_red}{transparent}{black}{Physikalische\\{}Chemie I}
		\drawmodule{3}{tetris_yellow}{transparent}{black}{CiS-\\{}Proseminar}
		\drawmodule{9}{tetris_gray}{transparent}{black}{Mathematik I für Physiker}
	\drawsemester{2. Semester\\(SoSe)}
		\drawmodule{9}{tetris_blue}{transparent}{black}{Formale Grundlagen\\der Informatik I}
		\drawmodule{9}{tetris_red}{transparent}{black}{Organische Chemie}
		\drawmodule{4.5}{tetris_red}{transparent}{black}{Physikalische\\{}Chemie II}
		\drawmodule{9}{tetris_gray}{transparent}{black}{Mathematik II für Physiker}
	\drawsemester{3. Semester\\(WiSe)}
		\drawmodule{6}{tetris_blue}{transparent}{black}{Algorithmen und\\{}Datenstrukturen}
		\drawmodule{6}{tetris_blue}{transparent}{black}{Grundlagen von\\{}Datenbanken}
		\drawmodule{3}{tetris_red}{transparent}{black}{Einführung\\{}in die\\[1.5pt]Medizinische\\[1.5pt]Chemie}
		\drawmodule{3}{tetris_red}{transparent}{black}{Einführung\\{}in die\\[1.5pt]Biochemie}
		\drawmodule{9}{tetris_gray}{transparent}{black}{Numerische Mathematik}
	\drawsemester{4. Semester\\(SoSe)}
		\drawmodule{6}{tetris_blue}{transparent}{black}{Softwareentwicklung II}
		\drawmodule{9}{tetris_blue}{transparent}{black}{Programmierung für\\{}Naturwissenschaften}
		\drawmodule{9}{tetris_red}{transparent}{black}{Wahlpflicht 3\\{}Vertiefung Chemie oder Biochemie}
		\drawmodule{6}{tetris_gray}{transparent}{black}{Stochastik}
	\drawsemester{5. Semester\\(WiSe)}
		\drawmodule{9}{white}{black}{black}{Wahlpflicht 2\\Mathematik / Informatik}
		\drawmodule{12}{tetris_red}{transparent}{black}{Wahlpflicht 3\\{}Vertiefung Chemie oder Biochemie}
		\drawmodule{9}{white}{black}{black}{Wahlpflicht 1\\Mathematik III für Physiker /\\Formale Grundl. d. Informatik II}
	\drawsemester{6. Semester\\(SoSe)}
		\drawmodule{9}{white}{black}{black}{Wahlpflicht 2\\Mathematik / Informatik}
		\drawmodule{6}{tetris_yellow}{transparent}{black}{Projekt\\CiS Biochemie}
		\drawmodule{3}{tetris_yellow}{transparent}{black}{CiS-\\Seminar}
		\drawmodule{12}{tetris_yellow}{transparent}{black}{Abschlussmodul\\(Bachelorarbeit)}
\end{tetris}
