\begin{tetris}[msc_bioinformatik]
	\drawsemester{1. Semester\\(WiSe)}
		\drawmodule{6}{white}{black}{black}{Angleichung}
		\drawmodule{6}{white}{black}{black}{Angleichung}
		\drawmodule{6}{white}{black}{black}{Angleichung}
		\drawmodule{6}{tetris_yellow}{transparent}{black}{Gr. d. Sequenzanalyse\\{}oder\\{}Gr. d. Strukturanalyse}
		\drawmodule{6}{tetris_yellow}{transparent}{black}{Gr. d. Strukturanalyse\\{}oder\\{}Gr. d. Chemieinformatik}
	\drawsemester{2. Semester\\(SoSe)}
		\drawmodule{9}{tetris_blue}{transparent}{black}{Informatik}
		\drawmodule{9}{tetris_yellow}{transparent}{black}{Angewandte Bioinformatik}
		\drawmodule{6}{tetris_yellow}{transparent}{black}{Gr. d. Sequenzanalyse\\{}oder\\{}Gr. d. Strukturanalyse}
		\drawmodule{6}{tetris_yellow}{transparent}{black}{Gr. d. Strukturanalyse\\{}oder\\{}Gr. d. Chemieinformatik}
	\drawsemester{3. Semester\\(WiSe)}
		\drawmodule{6}{tetris_yellow}{transparent}{black}{Genominformatik}
		\drawmodule{6}{tetris_yellow}{transparent}{black}{Struktur\\{}und\\{}Simulation}
		\drawmodule{6}{tetris_yellow}{transparent}{black}{Chemieinformatik\\{}und\\{}Wirkstoffentwurf}
		\drawmodule{6}{white}{black}{black}{Wahlpflicht\\{}Informatik /\\{}Lebenswissenschaften}
		\drawmodule{6}{white}{black}{black}{Freier Wahlbereich}
	\drawsemester{4. Semester\\(SoSe)}
		\drawmodule{3}{tetris_yellow}{transparent}{black}{Seminar\\{}Bioinf.}
		\drawmodule{9}{tetris_yellow}{transparent}{black}{Projekt Bioinformatik}
		\drawmodule{9}{white}{black}{black}{Wahlpflicht\\{}Informatik / Lebenswissenschaften}
		\drawmodule{9}{white}{black}{black}{Wahlpflicht\\{}Informatik / Lebenswissenschaften}
	\drawsemester{5. Semester\\(WiSe)}
		\drawmodule{30}{tetris_yellow}{transparent}{black}{Abschlussmodul (Masterarbeit)}
\end{tetris}