\begin{tetris}[bsc_cis_physik]
	\drawsemester{1. Semester\\(WiSe)}
		\drawmodule{6}{tetris_blue}{transparent}{black}{Softwareentwicklung I}
		\drawmodule{3}{tetris_yellow}{transparent}{black}{CiS-\\Proseminar}
		\drawmodule{12}{tetris_red}{transparent}{black}{Physik I}
		\drawmodule{9}{tetris_gray}{transparent}{black}{Mathematik I für Physiker}
	\drawsemester{2. Semester\\(SoSe)}
		\drawmodule{9}{tetris_blue}{transparent}{black}{Formale Grundlagen\\der Informatik I}
		\drawmodule{12}{tetris_red}{transparent}{black}{Physik II}
		\drawmodule{9}{tetris_gray}{transparent}{black}{Mathematik II für Physiker}
	\drawsemester{3. Semester\\(WiSe)}
		\drawmodule{6}{tetris_blue}{transparent}{black}{Algorithmen und\\Datenstrukturen}
		\drawmodule{6}{tetris_blue}{transparent}{black}{Grundlagen von\\Datenbanken}
		\drawmodule{8}{tetris_red}{transparent}{black}{Physikalisches Praktikum I}
		\drawmodule{9}{tetris_gray}{transparent}{black}{Numerische Mathematik}
	\drawsemester{4. Semester\\(SoSe)}
		\drawmodule{6}{tetris_blue}{transparent}{black}{Softwareentwicklung II}
		\drawmodule{9}{tetris_blue}{transparent}{black}{Programmierung für\\Naturwissenschaften}
		\drawmodule{9}{tetris_red}{transparent}{black}{Theoretische Physik II}
		\drawmodule{6}{tetris_gray}{transparent}{black}{Stochastik}
	\drawsemester{5. Semester\\(WiSe)}
		\drawmodule{9}{white}{black}{black}{Wahlpflicht 2\\Mathematik / Informatik / Physik}
		\drawmodule{6}{tetris_yellow}{transparent}{black}{Computational\\Physics}
		\drawmodule{6}{tetris_yellow}{transparent}{black}{Projekt\\CiS Physik}
		\drawmodule{9}{white}{black}{black}{Wahlpflicht 1\\Mathematik III für Physiker /\\Formale Grundl. d. Informatik II}
	\drawsemester{6. Semester\\(SoSe)}
		\drawmodule{9}{white}{black}{black}{Wahlpflicht 2\\Mathematik / Informatik / Physik}
		\drawmodule{7}{tetris_red}{transparent}{black}{Wahlpflicht 3\\Physik}
		\drawmodule{3}{tetris_yellow}{transparent}{black}{CiS-\\Seminar}
		\drawmodule{12}{tetris_yellow}{transparent}{black}{Abschlussmodul\\(Bachelorarbeit)}
\end{tetris}
