\begin{tetris}[bsc_informatik]
	\drawsemester{1. Semester\\(WiSe)}
		\drawmodule{6}{tetris_blue}{transparent}{black}{Softwareentwicklung I}
		\drawdummy{9}
		\drawmodule{9}{tetris_blue}{transparent}{black}{Rechnerstrukturen}
		\drawmodule{6}{tetris_blue}{transparent}{black}{Informatik im\\{}Kontext}
	\drawsemester{2. Semester\\(SoSe)}
		\drawmodule{6}{tetris_blue}{transparent}{black}{Softwareentwicklung II}
		\drawdummy{9}
		\drawmodulemulti{2}{tetris_gray}{transparent}{black}{Mathematik für Studierende\\{}der Informatik}
		\drawmodule{3}{white}{black}{black}{Methoden-\\{}kompetenz}
		\drawmodule{3}{tetris_blue}{transparent}{black}{Proseminar}
		\drawmodule{9}{tetris_blue}{transparent}{black}{Formale Grundlagen\\{}der Informatik I}
	\drawsemester{3. Semester\\(WiSe)}
		\drawmodule{6}{tetris_blue}{transparent}{black}{Algorithmen und\\{}Datenstrukturen}
		\drawmodule{24}{white}{black}{black}{Wahlpflicht}
	\drawsemester{4. Semester\\(SoSe)}
		\drawmodule{6}{tetris_blue}{transparent}{black}{Praktikum}
		\drawmodule{24}{white}{black}{black}{Wahlpflicht}
	\drawsemester{5. Semester\\(WiSe)}
		\drawmodule{9}{white}{black}{black}{Wahlpflicht}
		\drawmodule{9}{white}{black}{black}{Freier Wahlbereich}
		\drawmodule{9}{tetris_blue}{transparent}{black}{Projekt}
		\drawmodule{3}{tetris_blue}{transparent}{black}{Seminar}
	\drawsemester{6. Semester\\(SoSe)}
		\drawmodule{9}{white}{black}{black}{Wahlpflicht}
		\drawmodule{9}{white}{black}{black}{Freier Wahlbereich}
		\drawmodule{12}{tetris_blue}{transparent}{black}{Abschlussmodul\\{}(Bachelorarbeit)}
\end{tetris}
