\begin{tetris}[msc_informatik]
	\drawsemester{1. Semester\\(WiSe)}
		\drawmodule{9}{tetris_blue}{transparent}{black}{Wahlpflicht Theorie}
		\drawmodule{9}{tetris_blue}{transparent}{black}{Wahlpflicht}
		\drawmodule{6}{tetris_blue}{transparent}{black}{Vertiefung\\Informatik}
		\drawmodule{6}{white}{black}{black}{Freier\\Wahlbereich}
	\drawsemester{2. Semester\\(SoSe)}
		\drawdummy{6}
		\drawmodule{9}{tetris_blue}{transparent}{black}{Wahlpflicht}
		\drawmodule{6}{tetris_blue}{transparent}{black}{Vertiefung\\Informatik}
		\drawmodule{9}{white}{black}{black}{Freier\\Wahlbereich}
	\drawsemester{3. Semester\\(WiSe)}
		\drawdummy{6}
		\drawmodulemulti{2}{tetris_blue}{transparent}{black}{Projekt}
		\drawintegrated{2}{1}{3}{Seminar}
		\drawmodule{9}{tetris_blue}{transparent}{black}{Wahlpflicht}
		\drawmodule{6}{tetris_blue}{transparent}{black}{Vertiefung\\Informatik}
		\drawmodule{9}{white}{black}{black}{Freier\\Wahlbereich}
	\drawsemester{4. Semester\\(SoSe)}
		\drawmodule{30}{tetris_blue}{transparent}{black}{Abschlussmodul (Masterarbeit)}
\end{tetris}
