\begin{tetris}[msc_physik]
	\drawsemester{1. Semester\\(WiSe)}
		\drawmodule{24}{tetris_red}{transparent}{black}{Vertiefung Physik}
		\drawmodule{6}{white}{black}{black}{Freier Wahlbereich}		
	\drawsemester{2. Semester\\(SoSe)}
		\drawmodule{24}{tetris_red}{transparent}{black}{Vertiefung Physik}
		\drawmodule{6}{white}{black}{black}{Freier Wahlbereich}		
	\drawsemester{3. Semester\\(WiSe)}
		\drawmodule{15}{tetris_red}{transparent}{black}{Einarbeitungsprojekt}
		\drawmodule{15}{tetris_red}{transparent}{black}{Vorbereitungsprojekt}
		\drawintegrated{1}{1}{3}{Seminar}
	\drawsemester{4. Semester\\(SoSe)}
		\drawmodule{30}{tetris_red}{transparent}{black}{Abschlussmodul (Masterarbeit)}
\end{tetris}
